# Generated by Django 5.2.2 on 2025-06-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_administrador_pin_alcohol_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='pin',
        ),
    ]
