# Generated by Django 5.2.2 on 2025-06-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_administrador_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
