# Generated by Django 5.2.2 on 2025-06-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_administrador_pin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alcohol',
            table='alcohol',
        ),
    ]
