# Generated by Django 5.2.2 on 2025-06-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_alcohol_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alcohol',
            table='alcohol',
        ),
    ]
