# Generated by Django 5.2.2 on 2025-06-15 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_alcohol_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idadministrador', models.ForeignKey(blank=True, db_column='idadministrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.administrador')),
                ('idbarra', models.ForeignKey(blank=True, db_column='idbarra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.barra')),
            ],
            options={
                'db_table': 'bartender',
            },
        ),
    ]
