# Generated by Django 5.2.2 on 2025-06-15 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bartender'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='pin_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
