# Generated by Django 5.2.2 on 2025-06-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_administrador_pin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadealcohol',
            name='idadministrador',
            field=models.ForeignKey(blank=True, db_column='idadministrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.administrador'),
        ),
    ]
