# Generated by Django 5.2.2 on 2025-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_listadealcohol_idadministrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartender',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
