# Generated by Django 5.2.2 on 2025-06-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_bartender_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ia', models.FloatField()),
                ('stock_normal', models.IntegerField()),
                ('alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.alcohol')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.reporte')),
            ],
        ),
    ]
