# Generated by Django 5.2.2 on 2025-06-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_inventariofinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariofinal',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='myapp.reporte'),
        ),
    ]
